from PIL import Image
from PIL import ImageFilter

im0 = Image.open('Data-science.jpg')

#im = im0.filter(ImageFilter.BLUR)
#im.save('Data-science-training-blur.jpg')

#im = im0.filter(ImageFilter.CONTOUR)
#im.save('Data-science-training-contour.jpg')
#im = im0.filter(ImageFilter.DETAIL)
#im.save('Data-science-training-detail.jpg')
#im = im0.filter(ImageFilter.EDGE_ENHANCE)
#im.save('Data-science-training-edge-enhance.jpg')
#im = im0.filter(ImageFilter.EDGE_ENHANCE_MORE)
#im.save('Data-science-training-edge-enhance-more.jpg')
#im = im0.filter(ImageFilter.EMBOSS)
#im.save('Data-science-training-EMBOSS.jpg')
#im = im0.filter(ImageFilter.FIND_EDGES)
#im.save('Data-science-training-find-edges.jpg')
#im = im0.filter(ImageFilter.SMOOTH)
#im.save('Data-science-training-SMOOTH.jpg')
#im = im0.filter(ImageFilter.SMOOTH_MORE)
#im.save('Data-science-training-SMOOTH_MORE.jpg')
#im = im0.filter(ImageFilter.SHARPEN)
#im.save('Data-science-training-SHARPEN.jpg')
#im = im0.filter(ImageFilter.GaussianBlur(radius=4))
#im.save('Data-science-training-GaussianBlurrd4.jpg')
#im = im0.filter(ImageFilter.GaussianBlur(radius=10))
#im.save('Data-science-training-GaussianBlurrd10.jpg')
#im = im0.filter(ImageFilter.BoxBlur(5))
#im.save('Data-science-training-BoxBlur.jpg')
##im.save('Data-science-training-BoxBlur2.jpg')
im = im0.filter(ImageFilter.UnsharpMask(radius=10, percent=500, threshold=3))
im.save('Data-science-training-UnsharpMask.jpg')
im.show()
